### ISSUE TITLE
using P2P AS a login method 

### ISSUE THREAD

**Issue by bii10** [khoanguyen-3fc/dh-p2p#1]
hi sir i was wondering can add a new function that will allow you to use SN to login instead of using only RTSP protocol and keep the connection alive and thank you

**Comment by khoanguyen-3fc** [comment]
Could you please explain more clearly?

In this context, I've employed RTSP as a sample protocol to develop and finalize the server. It's important to note that I didn't implement the RTSP protocol, instead, I've used `ffplay`, an RTSP client, for demonstration purposes.

The code is intentionally designed to be protocol-independent, and after the PTCP handshake, it functions solely as a proxy/tunneling server. This flexibility enables connection using any client to any available port on the device.

**Comment by khoanguyen-3fc** [comment]
Could you please explain more clearly?

In this context, I've employed RTSP as a sample protocol to develop and finalize the server. It's important to note that I didn't implement the RTSP protocol, instead, I've used `ffplay`, an RTSP client, for demonstration purposes.

The code is intentionally designed to be protocol-independent, and after the PTCP handshake, it functions solely as a proxy/tunneling server. This flexibility enables connection using any client to any available port on the device.

As you can see in this snippet, each client connection has its own realm tunneling to a specific port on the device.

https://github.com/khoanguyen-3fc/dh-p2p/blob/41fda6dccde40a825249a781afcac02991aba480/main.py#L167-L175

**Comment by bii10** [comment]
oh i see thank you for your explanation , personally i was looking for a way to use SN instead of my ip address as login method , which i failed , looking into SDK and documentation etc....  dahua itself didn't provided any actual details of how you can use p2p and use my own SN a long with ( username and password ) to login into my device 
so i appreciate it if you can help me with it

**Comment by khoanguyen-3fc** [comment]
Which camera service (e.g., RTSP, HTTP, ...) would you like to access after logging in?

Upon examining the code, you'll find how I establish a connection to the device using P2P with SN.

I'm currently working on technical diagrams. In brief, the application and the device utilize an external service (easy4ipcloud) to discover each other's IP, initiate communication requests, and then, after the handshake, utilize a protocol called PTCP for encapsulation.

**Comment by bii10** [comment]
yes i found it already thank you , i was wondering do you have an email or something like that i would like to contact you

**Comment by khoanguyen-3fc** [comment]
Glad to hear you found what you needed!

For project-related discussions, let's keep it here on GitHub. Feel free to continue chatting on this issue, and I'll help out as best I can.

**Comment by matthew9991** [comment]
Hi guys , i don't have enough knowledge about this topic and it's seems complicated and code kinda complex , about the usage of it , when i use it let's say "python  main.py my_SN -u username -p password "
it's stopping in the end saying " Ready to connect ", what have i done wrong ?  so if you mind please explain the usage of it and the potential of it as well

**Comment by bii10** [comment]
actually i am facing one issue usually only when i am using windows only , it doesn't happen in Linux which is  : 
Traceback (most recent call last):
  File "/home/pc/dh-p2p/main.py", line 269, in <module>
    main(args.serial, args.username, args.password, args.debug)
  File "/home/pc/dh-p2p/main.py", line 127, in main
    res = device_remote.read_ptcp()
  File "/home/pc/dh-p2p/helpers.py", line 183, in read_ptcp
    res = PTCP.parse(data)
  File "/home/pc/dh-p2p/helpers.py", line 95, in parse
    raise ValueError("Invalid magic")
ValueError: Invalid magic

**Comment by khoanguyen-3fc** [comment]
Could you please enable debug mode, try again, and share the full log? Up to the step mentioned, neither a username/password nor `ffplay` is required.

**Comment by khoanguyen-3fc** [comment]
@matthew9991 What's your operating system, and do you have `ffmpeg` / `ffplay` installed?

You can try again with the debug `-d` argument. It will automatically use `ffplay` to display the stream:

```bash
main.py -u USERNAME -p PASSWORD -d serial
```

Without the debug option, you'll need to manually use an RTSP client to connect to the listened port.

https://github.com/khoanguyen-3fc/dh-p2p/blob/86331426c0e7a9cef698308b8036ffdc22c2fe58/main.py#L19-L31

**Comment by bii10** [comment]
> Could you please enable debug mode, try again, and share the full log? Up to the step mentioned, neither a username/password nor `ffplay` is required.

hey bro i would like to contact you about something private and can't discuss it here , so if you don't mind can u please , tell me how to contact you privately

**Comment by khoanguyen-3fc** [comment]
@bii10 At least, could you try sharing more about any non-private part? Alternatively, you can censor any information you prefer not to disclose. It would really help me and others understand the situation better.

@matthew9991 Did the explanation above help? I've also updated the README. Do you have any questions in advance?
