### ISSUE TITLE
HTTP/1.1 401 Unauthorized

### ISSUE THREAD

**Issue by craftingforever** [khoanguyen-3fc/dh-p2p#10]
I’m facing a "HTTP/1.1 401 Unauthorized" error, and look like it stopped working , and is there's any ways to fix it ?

**Comment by khoanguyen-3fc** [comment]
Did you update to the latest code? We recently updated the credentials (https://github.com/khoanguyen-3fc/dh-p2p/commit/f6478bfd013528783263e263b8aec40c7e1e9245)
