### ISSUE TITLE
user and key are not valid anymore

### ISSUE THREAD

**Issue by bpietroiu** [khoanguyen-3fc/dh-p2p#9]
user P2PClient and the supplied key is not valid, results in a 403 Forbidden response.

I dumped another set out of SmartPSSLite 

Edit: 
 
USERNAME = "cba1b29e32cb17aa46b8ff9e73c7f40b"; // used to be "P2PClient";
USERKEY = "996103384cdf19179e19243e959bbf8b";// used to be "YXQ3Mahe-5H-R1Z_";

**Comment by hadenpereira** [comment]
@bpietroiu  Could you please share it?

**Comment by bpietroiu** [comment]
USERNAME = "cba1b29e32cb17aa46b8ff9e73c7f40b"; // used to be "P2PClient";
USERKEY = "996103384cdf19179e19243e959bbf8b";//  used to be "YXQ3Mahe-5H-R1Z_";

I have also ported this code to C#, if needed I can create a repo for it

**Comment by DanielAlegriaLino** [comment]
> USERNAME = "cba1b29e32cb17aa46b8ff9e73c7f40b"; // used to be "P2PClient";
> 
> USERKEY = "996103384cdf19179e19243e959bbf8b";//  used to be "YXQ3Mahe-5H-R1Z_";
> 
> 
> 
> I have also ported this code to C#, if needed I can create a repo for it
> 
> 

Yep, it would be nice if you share it.

**Comment by khoanguyen-3fc** [comment]
Let me check if it still works with my old client.

**Comment by aivavia** [comment]
still no luck?

**Comment by DanielAlegriaLino** [comment]
It suddently stopped working for me

**Comment by khoanguyen-3fc** [comment]
I just checked, and my camera still works with the old credentials. However, it also works with the new ones, so updating to the new credentials will help more users.

I’m doing a quick test now and will push the code later.

**Comment by sbuzza** [comment]
> USERNAME = "cba1b29e32cb17aa46b8ff9e73c7f40b"; // used to be "P2PClient"; USERKEY = "996103384cdf19179e19243e959bbf8b";// used to be "YXQ3Mahe-5H-R1Z_";
> 
> I have also ported this code to C#, if needed I can create a repo for it

@bpietroiu possible for you to share the C# port please? Thanks

**Comment by khoanguyen-3fc** [comment]
I see that Dahua already provides some SDKs for the .NET platform [here](https://depp.dahuasecurity.com/integration/guide/download/DSS%20SDK). Has anyone tried them to see if they cover our use case?

**Comment by sbuzza** [comment]
As far as I know, none of the Dahua SDK have connecting via SN (P2P) functionality. Have tried them extensively and read up on them deeply. If someone knows otherwise, please share/direct. Thanks

**Comment by khoanguyen-3fc** [comment]
As a quick look, I found that DPSDK includes `P2PDll.dll`, which seems to contain functionality for P2P connectivity. However, it might be used internally and not exposed for direct use.

<img width="342" alt="image" src="https://github.com/user-attachments/assets/39884022-1b5b-47ed-9786-98da3a986744" />
